language: python

addons:
  firefox: "52.0"
  postgresql: "9.5"

services:
  - postgresql

matrix:
  include:
  - python: "3.4"
    env: USE_CONDA=true
  - python: "3.5"
    env: USE_CONDA=true COVERALLS=true FLAKE8=true
  - python: "3.4"
    env: USE_PIP=true

before_script:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - tar -xvzf geckodriver-v0.11.1-linux64.tar.gz
  - chmod +x geckodriver && sudo mv geckodriver /usr/local/bin
  # reference travis docs
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

install:
  - if [ "$USE_PIP" = "true" ]; then
    echo "---- Install dependencies with pip";
    pip install --upgrade pip;
    pip install -r hbgd_data_store_server/requirements.txt;
    fi
  - if [ "$USE_CONDA" = "true" ]; then
    echo "---- Install miniconda";
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    bash miniconda.sh -b -p $HOME/miniconda;
    export PATH="$HOME/miniconda/bin:$PATH";
    hash -r;
    echo "---- Setup conda";
    conda config --set always_yes yes --set changeps1 no;
    conda update -q conda;
    echo "---- Install dependencies with conda";
    conda create -n hbgd-data-store-server python=$TRAVIS_PYTHON_VERSION;
    source activate hbgd-data-store-server;
    conda env update -f environment.yml;
    fi

script:
  # Django environment variables
  - export SECRET_KEY="ASECRET"
  # Build docs
  - pushd hbgd_data_store_server/docs
  - make html
  - popd
  # Run tests
  - cd hbgd_data_store_server
  - python manage.py collectstatic --noinput
  - if [ "$COVERALLS" = "true" ] && [ "$FLAKE8" = "true" ] ; then
    python manage.py test --driver Firefox --cov --cov-report term-missing -v --flake8;
    else
    python manage.py test --driver Firefox -v;
    fi

after_success:
  - if [ "$COVERALLS" = "true" ]; then coveralls; fi
